//! robots.txt mirroring: Gemini's companion-spec robots.txt → a standard
//! web robots.txt for the rendered HTML tree (BUILD-PLAN C3; ADR 0004
//! "mirrors a web robots.txt into the HTML output").
//!
//! **These are not the same format, which is the whole problem this
//! module exists to solve** (design brief §5.9 left the definition open;
//! it is settled here). Gemini's companion spec defines *virtual*
//! user-agents describing a crawler's purpose — `archiver`, `indexer`,
//! `researcher`, `webproxy` — none of which mean anything to a web
//! crawler. A verbatim copy would therefore be the dangerous option: an
//! operator who wrote `User-agent: indexer` + `Disallow: /private` to
//! keep a path out of search engines would find Googlebot ignoring that
//! rule entirely (it matches no group it recognises) and indexing the
//! path anyway. The operator's intent would be silently lost, in the
//! direction that leaks.
//!
//! **So the translation unions every `Disallow` across every agent group
//! into a single `User-agent: *` group.** The asymmetry is deliberate:
//! under-blocking exposes content the operator explicitly asked a
//! crawler not to take, while over-blocking merely leaves a page
//! unindexed. When the two error directions are unequal, the mirror
//! errs toward the recoverable one.
//!
//! No `content/robots.txt` means no web `robots.txt` is emitted at all —
//! usv does not invent crawler policy the operator never wrote.

/// Translate a Gemini companion-spec robots.txt into a web robots.txt.
/// Returns `None` when the input contains no `Disallow` rules at all, so
/// the caller writes no file rather than an empty, meaningless one.
///
/// The parse is deliberately lenient in the same way real robots.txt
/// parsers are: unknown directives, blank lines, and `#` comments are
/// skipped rather than treated as errors, because a malformed line in a
/// content file must never fail a render.
pub fn to_web_robots(gemini_robots: &str) -> Option<String> {
    let mut disallowed: Vec<&str> = Vec::new();
    for line in gemini_robots.lines() {
        let line = line.split('#').next().unwrap_or("").trim();
        let Some((field, value)) = line.split_once(':') else {
            continue;
        };
        if !field.trim().eq_ignore_ascii_case("disallow") {
            continue;
        }
        let path = value.trim();
        // An empty `Disallow:` means "allow everything" for that group —
        // it is not a path, and unioning it in would disallow nothing
        // while looking like it did something.
        if path.is_empty() {
            continue;
        }
        if !disallowed.contains(&path) {
            disallowed.push(path);
        }
    }

    if disallowed.is_empty() {
        return None;
    }

    let mut out = String::from(
        "# Generated by Unseen Servant from this capsule's Gemini robots.txt.\n\
         # Gemini's companion spec uses virtual user-agents (archiver, indexer,\n\
         # researcher, webproxy) that web crawlers do not recognise, so every\n\
         # Disallow rule is unioned into one group here: a rule the operator\n\
         # wrote for any Gemini crawler applies to every web crawler.\n\
         # Edit the capsule's robots.txt, not this file — it is regenerated\n\
         # on every render.\n\n\
         User-agent: *\n",
    );
    for path in disallowed {
        out.push_str("Disallow: ");
        out.push_str(path);
        out.push('\n');
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_rules_produces_no_file() {
        assert_eq!(to_web_robots(""), None);
        assert_eq!(to_web_robots("# just a comment\n"), None);
        assert_eq!(to_web_robots("User-agent: *\n"), None);
    }

    #[test]
    fn empty_disallow_means_allow_all_and_is_not_a_path() {
        // "Disallow:" with no value permits everything; it must not be
        // unioned in as if it were a rule.
        assert_eq!(to_web_robots("User-agent: *\nDisallow:\n"), None);
    }

    #[test]
    fn a_single_rule_becomes_a_wildcard_group() {
        let out = to_web_robots("User-agent: indexer\nDisallow: /private\n").expect("has rules");
        assert!(out.contains("User-agent: *"));
        assert!(out.contains("Disallow: /private"));
    }

    #[test]
    fn rules_across_virtual_agents_are_unioned() {
        // The core translation: three Gemini-specific groups collapse to
        // one web group carrying all three paths, because none of those
        // agent names would match anything on the web.
        let gemini = "\
User-agent: indexer
Disallow: /no-index

User-agent: archiver
Disallow: /no-archive

User-agent: researcher
Disallow: /no-research
";
        let out = to_web_robots(gemini).expect("has rules");
        assert_eq!(out.matches("User-agent:").count(), 1);
        assert!(out.contains("Disallow: /no-index"));
        assert!(out.contains("Disallow: /no-archive"));
        assert!(out.contains("Disallow: /no-research"));
    }

    #[test]
    fn duplicate_paths_are_emitted_once() {
        let gemini = "\
User-agent: indexer
Disallow: /secret
User-agent: archiver
Disallow: /secret
";
        let out = to_web_robots(gemini).expect("has rules");
        assert_eq!(out.matches("Disallow: /secret").count(), 1);
    }

    #[test]
    fn comments_and_blank_lines_are_ignored() {
        let out = to_web_robots(
            "# a comment\n\n  \nUser-agent: *  # trailing comment\nDisallow: /x  # here too\n",
        )
        .expect("has rules");
        assert!(out.contains("Disallow: /x"));
        assert!(!out.contains("trailing comment"));
    }

    #[test]
    fn malformed_lines_never_panic_or_fail() {
        for input in ["::::", "Disallow", "\0", "Disallow: \u{1F600}", "a:b:c:d"] {
            let _ = to_web_robots(input);
        }
    }

    #[test]
    fn case_insensitive_directive_names() {
        let out = to_web_robots("DISALLOW: /x\n").expect("has rules");
        assert!(out.contains("Disallow: /x"));
    }

    #[test]
    fn output_tells_the_operator_where_to_edit() {
        // A generated file that doesn't say it's generated invites
        // someone to edit it and lose the change on the next render.
        let out = to_web_robots("Disallow: /x\n").expect("has rules");
        assert!(out.contains("regenerated"));
    }
}
